### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by RuntyCascade** [koush/scrypted-google-device-access#1]
getting "Error 400: redirect_uri_mismatch" when trying to log in. Have added client id, client secret, and project id prior to logging in. all information provided to plugin was accessed by following the https://www.home-assistant.io/integrations/nest/ link given when originally installing plugin.

console:
starting plugin @scrypted/google-device-access 0.0.41
token error SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at GoogleSmartDeviceAccess.loadToken (/src/main.ts:403:59)
    at GoogleSmartDeviceAccess.authGet (/src/main.ts:449:20)
    at GoogleSmartDeviceAccess.apply (/src/main.ts:289:37)
    at invokeFunc (/node_modules/lodash/debounce.js:95:19)
    at leadingEdge (/node_modules/lodash/debounce.js:105:22)
    at GoogleSmartDeviceAccess.refreshThrottled (/node_modules/lodash/debounce.js:172:16)
    at GoogleSmartDeviceAccess.refresh (/src/main.ts:423:21)
    at GoogleSmartDeviceAccess.discoverDevices (/src/main.ts:473:35)
    at new GoogleSmartDeviceAccess (/src/main.ts:311:14)
plugin successfully loaded

**Comment by koush** [comment]
wrong repo https://github.com/koush/scrypted/tree/main/plugins/google-device-access
